
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { HfInference } from 'https://esm.sh/@huggingface/inference@2.3.2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Use the provided API keys
const HUGGING_FACE_ACCESS_TOKEN = "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";
const PIXABAY_API_KEY = "49332633-dce2019b5134e9a672d2af561";

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { prompt, profileId } = await req.json();
    
    if (!prompt) {
      throw new Error('Prompt is required');
    }

    if (!profileId) {
      throw new Error('Profile ID is required');
    }
    
    console.log('Finding best image for prompt:', prompt, 'Profile ID:', profileId);

    let selectedImage = null;
    let imageSource = null;
    let imageUrl = null;

    // Try Pixabay first with improved search terms
    try {
      console.log('Querying Pixabay API for:', prompt);
      
      // Use the full prompt for better search results
      const cleanedPrompt = prompt.replace(/[^\w\s]/gi, ''); // Remove special characters
      const pixabayUrl = `https://pixabay.com/api/?key=${PIXABAY_API_KEY}&q=${encodeURIComponent(cleanedPrompt)}&image_type=photo&per_page=5&safesearch=true&order=relevance`;
      
      console.log('Pixabay search URL:', pixabayUrl);
      const pixabayResponse = await fetch(pixabayUrl);
      const pixabayData = await pixabayResponse.json();
      
      if (pixabayData.hits && pixabayData.hits.length > 0) {
        // Select the first (most relevant) image from Pixabay
        const image = pixabayData.hits[0];
        imageUrl = image.largeImageURL;
        imageSource = 'pixabay';
        console.log('Found suitable image on Pixabay:', image.tags);
      } else {
        console.log('No suitable images found on Pixabay, falling back to Hugging Face');
      }
    } catch (error) {
      console.error('Error querying Pixabay:', error);
      console.log('Falling back to Hugging Face due to Pixabay error');
    }

    // If no suitable image found on Pixabay, use Hugging Face with enhanced prompt
    if (!imageUrl) {
      console.log('Generating image with Hugging Face for prompt:', prompt);
      const hf = new HfInference(HUGGING_FACE_ACCESS_TOKEN);
      
      // Enhance prompt for better results
      const enhancedPrompt = `high quality, detailed image of ${prompt}`;
      console.log('Enhanced prompt for Hugging Face:', enhancedPrompt);

      // Using stable diffusion model for better quality and prompt relevance
      const image = await hf.textToImage({
        inputs: enhancedPrompt,
        model: 'runwayml/stable-diffusion-v1-5',
        parameters: {
          negative_prompt: "blurry, bad quality, distorted, deformed, ugly, low resolution",
          num_inference_steps: 30,  // Increased steps for better quality
          guidance_scale: 7.5,      // Increased guidance scale for prompt adherence
        }
      });

      if (!image) {
        throw new Error('No image was generated by Hugging Face');
      }

      console.log('Image generated successfully by Hugging Face, converting to base64');

      // Convert the blob to base64 string
      const arrayBuffer = await image.arrayBuffer();
      const base64 = btoa(String.fromCharCode(...new Uint8Array(arrayBuffer)));
      imageUrl = `data:image/png;base64,${base64}`;
      imageSource = 'huggingface';
    }

    console.log(`Successfully retrieved image from ${imageSource}`);

    return new Response(
      JSON.stringify({ imageUrl, source: imageSource }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('Error in multi-source-image function:', error);
    
    let statusCode = 500;
    let errorMessage = error.message || 'Failed to generate image';
    
    // More specific error handling
    if (error.message?.includes('rate limit')) {
      statusCode = 429;
      errorMessage = 'API rate limit exceeded. Please try again later.';
    } else if (error.message?.includes('invalid token')) {
      statusCode = 401;
      errorMessage = 'Invalid API token. Please check your API keys.';
    } else if (error.message?.includes('model not found')) {
      statusCode = 404;
      errorMessage = 'The AI model could not be loaded. Please try again.';
    }
    
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { 
        status: statusCode,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    );
  }
});
